name: release

on:
  push:
    branches:
      - release/*
    tags:
      - "v[0-9]+"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Exit if not on master branch
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ $CURRENT_BRANCH != master ]]; then
            exit -1
          fi
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g auto-changelog
      - name: Create Release Issue
        run: |
          ISSUE_TITLE=$(git tag $GITHUB_REF_NAME -l --format 'Release %(refname:short) by %(authorname)')
          ISSUE_BODY=$(npx auto-changelog --commit-limit false --template keepachangelog --hide-credit --sort-commits date-desc --stdout)
          gh issue create -t "$ISSUE_TITLE" -b "$ISSUE_BODY" -l "RELEASE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release Branch
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          RELEASE_BRANCH=release/$GITHUB_REF_NAME
          git branch $RELEASE_BRANCH $GITHUB_REF_NAME
      - name: Push Release Branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.RELEASE_BRANCH }}
