name: release

on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g auto-changelog
      - name: Create Release Issue
        run: |
          ISSUE_TITLE=$(git tag $GITHUB_REF_NAME -l --format 'Release %(refname:short) by %(authorname)')
          ISSUE_BODY=$(npx auto-changelog --commit-limit false --template keepachangelog --hide-credit --sort-commits date-desc --stdout)
          gh issue create -t "$ISSUE_TITLE" -b "$ISSUE_BODY" -l "RELEASE"
