name: update release

on:
  push:
    branches:
      - release/*

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g auto-changelog
      - name: Set Tag Name
        run: |
          TAG_NAME=$(echo $GITHUB_REF_NAME | cut -d'/' -f2)
          echo $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      - name: Find Release Issue
        id: find-issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'find-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          title-includes: '${{ env.TAG_NAME }}'
          labels: 'RELEASE'
      - name: Get Release Issue Number
        id: get-issue-number
        uses: actions/github-script@v6
        with:
          script: |
            const issues = JSON.parse('${{ steps.find-issue.outputs.issues }}');
            const issue = issues[0];
            return issue.number;
      - name: Edit Release Issue
        run: |
          COMMENT_BODY=$(npx auto-changelog --commit-limit false --template keepachangelog --hide-credit --sort-commits date-desc --stdout --unreleased)
          echo "${{ steps.get-issue-number.outputs.result }}"
          gh issue edit ${{ steps.get-issue-number.outputs.result }} -b "$COMMENT_BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
